In [25]:
from task_maker import create_task
import pandas as pd
from itertools import product
import numpy as np

In [26]:
filename = "task_template.json"

In [27]:
num_tasks = 500

dataset = []
for _ in range(num_tasks):
    task = create_task(filename)
    dataset.append(task)
df = pd.DataFrame(dataset)

In [28]:
df.head()

,red_cube_start,blue_cube_start,yellow_cube_start,green_cube_start,Text Question,block_for_task,cat,other_blocks,red_cube_goal,blue_cube_goal,yellow_cube_goal,green_cube_goal
0,"(0.3, 0.25, 0.02)","(0.0, 0.55, 0.02)","(0.15, 0.55, 0.02)","(0.3, 0.55, 0.02)","Take the block that is leftmost and place it between the blocks that are (0.15000000000000002, 0.0) from the yellow block and (-0.15000000000000002, 0.30000000000000004) from the red block",1,2,"[3, 2]","(0.3, 0.25, 0.02)","(-0.3, 0.25, 0.02)","(0.15, 0.55, 0.02)","(0.3, 0.55, 0.02)"
1,"(0.0, 0.4, 0.02)","(0.15, 0.25, 0.02)","(-0.15, 0.55, 0.02)","(-0.3, 0.25, 0.02)",Take the block that is coloured associated with war and place it at [-0.15 0.25],0,0,None,"(-0.15, 0.25, 0.02)","(0.15, 0.25, 0.02)","(-0.15, 0.55, 0.02)","(-0.3, 0.25, 0.02)"
2,"(-0.15, 0.55, 0.02)","(0.15, 0.55, 0.02)","(-0.15, 0.4, 0.02)","(0.3, 0.4, 0.02)",Take the block that is coloured the sad one and place it at [0. 0.55],1,0,None,"(-0.15, 0.55, 0.02)","(0.0, 0.55, 0.02)","(-0.15, 0.4, 0.02)","(0.3, 0.4, 0.02)"
3,"(-0.15, 0.25, 0.02)","(0.15, 0.55, 0.02)","(0.3, 0.4, 0.02)","(-0.3, 0.25, 0.02)",Take the block that is coloured butter-coloured and place it 2 horizontally and -2 vertically relative to the block that is highest,2,1,1,"(-0.15, 0.25, 0.02)","(0.15, 0.55, 0.02)","(2.15, -1.45, 0.02)","(-0.3, 0.25, 0.02)"
4,"(-0.3, 0.4, 0.02)","(0.15, 0.4, 0.02)","(0.15, 0.55, 0.02)","(0.3, 0.55, 0.02)",Take the block that is coloured banana-coloured and place it at [0.15 0.25],2,0,None,"(-0.3, 0.4, 0.02)","(0.15, 0.4, 0.02)","(0.15, 0.25, 0.02)","(0.3, 0.55, 0.02)"

In [29]:
def is_valid(x):
    
    end_locs = (np.array(x['red_cube_goal']), 
                np.array(x['blue_cube_goal']), 
                np.array(x['green_cube_goal']), 
                np.array(x['yellow_cube_goal']))
    indices = list(range(4))
    dists = []
    for a, b in product(indices, repeat=2):
        if a != b:
            dists.append(np.linalg.norm(end_locs[a] - end_locs[b]))
    return min(dists)

In [30]:
df['goal_dist'] = df.apply(is_valid, axis=1)

In [31]:
pd.set_option('display.max_colwidth', None)

In [32]:
df[df['goal_dist'] == 0]#[['Text Question'] + [i for i in df.columns.tolist() if 'goal' in i]]

Empty DataFrame
Columns: [red_cube_start, blue_cube_start, yellow_cube_start, green_cube_start, Text Question, block_for_task, cat, other_blocks, red_cube_goal, blue_cube_goal, yellow_cube_goal, green_cube_goal, goal_dist]
Index: []

In [33]:
df.to_csv("task_dataset.csv", index=False)

In [34]:
data = pd.read_csv('task_dataset.csv')

In [35]:
task_observations = []
for rs,bs,gs,ys in zip(data['red_cube_start'],data['blue_cube_start'],data['green_cube_start'],data['yellow_cube_start']):
    return_str = '' 
    return_str += '*** Observation *** \n'
    return_str +=  'Here is the initial position of each block and the end effector: \n'
    return_str += 'Red Cube: ' + str(eval(rs)[0:2]) + '\n'
    return_str += 'Green Cube: ' + str(eval(gs)[0:2]) + '\n'
    return_str += 'Blue Cube: ' + str(eval(bs)[0:2]) + '\n'
    return_str += 'Yellow Cube: ' + str(eval(ys)[0:2]) + '\n'
    return_str += 'End Effector: ' + '(0, 0.25)' + '\n'
    return_str += 'Note - the arm itself is at 0,0. Assume that the x-axis determines left and right and the y-axis top and bottom.'
    task_observations.append(return_str)
print(len(task_observations))
print(task_observations[0])

500
*** Observation ***
Here is the initial position of each block and the end effector:
Red Cube: (0.3, 0.25)
Green Cube: (0.3, 0.55)
Blue Cube: (0.0, 0.55)
Yellow Cube: (0.15, 0.55)
End Effector: (0, 0.25)
Note - the arm itself is at 0,0. Assume that the x-axis determines left and right and the y-axis top and bottom.

In [36]:
# sanity check
data['observation'] = task_observations
print(data.iloc[0])
data.iloc[0]['observation']

red_cube_start                                                                                                                                                                                                                                                                                                                           (0.3, 0.25, 0.02)
blue_cube_start                                                                                                                                                                                                                                                                                                                          (0.0, 0.55, 0.02)
yellow_cube_start                                                                                                                                                                                                                                                                                                                       (0.15, 0.55, 0.02)
green_cube_start                                                                                                                                                                                                                                                                                                                         (0.3, 0.55, 0.02)
Text Question                                                                                                                                                 Take the block that is leftmost and place it between the blocks that are (0.15000000000000002, 0.0) from the yellow block and (-0.15000000000000002, 0.30000000000000004) from the red block
block_for_task                                                                                                                                                                                                                                                                                                                                           1
cat                                                                                                                                                                                                                                                                                                                                                      2
other_blocks                                                                                                                                                                                                                                                                                                                                         [3 2]
red_cube_goal                                                                                                                                                                                                                                                                                                                            (0.3, 0.25, 0.02)
blue_cube_goal                                                                                                                                                                                                                                                                                                                          (-0.3, 0.25, 0.02)
yellow_cube_goal                                                                                                                                                                                                                                                                                                                        (0.15, 0.55, 0.02)
green_cube_goal                                                                                                                                                                                                                                                                                                                          (0.3, 0.55, 0.02)
goal_dist                                                                                                                                                                                                                                                                                                                                             0.15
observation          *** Observation *** \nHere is the initial position of each block and the end effector: \nRed Cube: (0.3, 0.25)\nGreen Cube: (0.3, 0.55)\nBlue Cube: (0.0, 0.55)\nYellow Cube: (0.15, 0.55)\nEnd Effector: (0, 0.25)\nNote - the arm itself is at 0,0. Assume that the x-axis determines left and right and the y-axis top and bottom.
Name: 0, dtype: object

'*** Observation *** \nHere is the initial position of each block and the end effector: \nRed Cube: (0.3, 0.25)\nGreen Cube: (0.3, 0.55)\nBlue Cube: (0.0, 0.55)\nYellow Cube: (0.15, 0.55)\nEnd Effector: (0, 0.25)\nNote - the arm itself is at 0,0. Assume that the x-axis determines left and right and the y-axis top and bottom.'

In [37]:
# saves
data.to_csv('task_dataset.csv')